---
version: '3'

vars:
  CC: gcc
  CC_FLAGS: "-Werror -Wextra -Wall -Wfree-nonheap-object -std=c17"
  EXECUTABLE_NAME: cerver
  DYN_LIBS_USED_PATH: "-L/usr/local/lib/standardloop"
  DYN_LIBS_USED: "-pthread -lstandardloop-logger -lstandardloop-util -lstandardloop-json"
  SOURCE_FILES:
    - cerver.c
    - thread/pool.c
    - thread/worker.c
    - thread/scheduler.c
    - http/handler.c
    - http/router.c
    - structures/queue/queue.c
    - http/response/codes.c
    - http/response/response.c
    - http/request/request.c
    - http/request/parser/body.c
    - http/request/parser/host.c
    - http/request/parser/path.c
    - http/request/parser/port.c
    - http/request/parser/query.c
    - http/request/parser/method.c
    - http/request/parser/headers.c 
    - http/request/parser/version.c
    - http/request/parserv2/parser.c
    - http/request/parserv2/lexer.c
    - http/request/parserv2/method.c


# Inputs
# - REPO_NAME
# - DYLIB_VERSION
# - DYLIB_NAME
download-dependency: &download-dependency |
  mkdir -p dependencies/tmp-{{.DYLIB_NAME}}
  cd dependencies/tmp-{{.DYLIB_NAME}}
  curl -O -J -L https://github.com/standardloop/{{.REPO_NAME}}/releases/download/v{{.DYLIB_VERSION}}/libstandardloop-{{.DYLIB_NAME}}.zip
  unzip libstandardloop-{{.DYLIB_NAME}}.zip
  sudo mkdir -p /usr/local/lib/standardloop/
  sudo mkdir -p /usr/local/include/standardloop/
  sudo mv libstandardloop-{{.DYLIB_NAME}}.dylib /usr/local/lib/standardloop/
  sudo mv {{.DYLIB_NAME}}.h /usr/local/include/standardloop/ && rm libstandardloop-{{.DYLIB_NAME}}.zip

tasks:
  default:
    silent: true
    deps:
      - build
      # - build:sanitize
      # - run

  dependencies:
    deps:
      - dependencies:logger
      - dependencies:util
      - dependencies:json

  dependencies:logger:
    vars:
      REPO_NAME: c-logger
      DYLIB_VERSION: 0.0.7
      DYLIB_NAME: logger
    cmds:
      - sudo -v
      - *download-dependency
    status:
      - otool -L /usr/local/lib/standardloop/libstandardloop-{{.DYLIB_NAME}}.dylib | head -n 2 | tail -n 1 | grep "current version {{.DYLIB_VERSION}}"
      - cat /usr/local/include/standardloop/{{.DYLIB_NAME}}.h | grep "STANDARDLOOP_{{.DYLIB_NAME | upper}}_H_VERSION \"{{.DYLIB_VERSION}}\""

  dependencies:util:
    vars:
      REPO_NAME: c-util
      DYLIB_VERSION: 0.0.3
      DYLIB_NAME: util
    cmds:
      - sudo -v
      - *download-dependency
    status:
      - otool -L /usr/local/lib/standardloop/libstandardloop-{{.DYLIB_NAME}}.dylib | head -n 2 | tail -n 1 | grep "current version {{.DYLIB_VERSION}}"
      - cat /usr/local/include/standardloop/{{.DYLIB_NAME}}.h | grep "STANDARDLOOP_{{.DYLIB_NAME | upper}}_H_VERSION \"{{.DYLIB_VERSION}}\""

  dependencies:json:
    vars:
      REPO_NAME: c-json
      DYLIB_VERSION: 0.0.4
      DYLIB_NAME: json
    cmds:
      - sudo -v
      - *download-dependency
    status:
      - otool -L /usr/local/lib/standardloop/libstandardloop-{{.DYLIB_NAME}}.dylib | head -n 2 | tail -n 1 | grep "current version {{.DYLIB_VERSION}}"
      - cat /usr/local/include/standardloop/{{.DYLIB_NAME}}.h | grep "STANDARDLOOP_{{.DYLIB_NAME | upper}}_H_VERSION \"{{.DYLIB_VERSION}}\""

  # dependencies:clean:
  #   cmds:


  build:
    deps:
      - dependencies
    cmds:
      - |
        {{.CC}} {{.CC_FLAGS}} \
        main.c \
        {{range .SOURCE_FILES}} {{.}} {{end}} \
        {{.DYN_LIBS_USED_PATH}} \
        {{.DYN_LIBS_USED}} \
        -o {{.EXECUTABLE_NAME}}
    sources:
      - ./**/*.c
    generates:
      - "{{.EXECUTABLE_NAME}}"
  
  run:
    deps:
      - build
    cmds:
      - ./{{.EXECUTABLE_NAME}}

  sanitize:
    deps:
      - run:sanitize

  build:sanitize:
    run: once
    deps:
      - dependencies
    cmds:
      - |
        {{.CC}} {{.CC_FLAGS}} \
        main.c \
        -fsanitize=address \
        -fno-omit-frame-pointer \
        {{range .SOURCE_FILES}} {{.}} {{end}} \
        {{.DYN_LIBS_USED_PATH}} \
        {{.DYN_LIBS_USED}} \
        -o {{.EXECUTABLE_NAME}}-sanitize
    sources:
      - ./**/*.c
    generates:
      - "{{.EXECUTABLE_NAME}}-sanitize"
  
  run:sanitize:
    deps:
      - build:sanitize
    cmds:
      - ./{{.EXECUTABLE_NAME}}-sanitize

  clean:
    allow_failures: true
    cmds:
      - rm -f {{.EXECUTABLE_NAME}}
      - rm -f {{.EXECUTABLE_NAME}}-debug
      - rm -f {{.EXECUTABLE_NAME}}-sanitize
      - rm -f {{.EXECUTABLE_NAME}} optimize
      - rm -f a.out

  leaks:cp:
    deps:
      - build
    cmds:
      - cp /usr/local/lib/standardloop/libstandardloop-util.dylib ./ # to get around sips we need to move dylibs to local dir :(
      - cp /usr/local/lib/standardloop/libstandardloop-json.dylib ./ # to get around sips we need to move dylibs to local dir :(
      - cp /usr/local/lib/standardloop/libstandardloop-logger.dylib ./ # to get around sips we need to move dylibs to local dir :(

  leaks:clean:
    cmds:
      - rm -f libstandardloop-logger.dylib
      - rm -f libstandardloop-json.dylib
      - rm -f libstandardloop-util.dylib
